name: React CI Workflow
run-name: triggered by @${{github.actor}}
on:
  push:
    branches: [main, hotfix*]
  pull_request:
    branches: [main]
jobs:
  build-check:
    name: CI for greeting app
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4
      - name: 2.Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: 3. Install NPM Dependencies
        run: npm i
      - name: 4. Run prod build
        run: npm run build
